export const ActionTypes = {
  FETCH_POSTS: 'posts/FETCH_POSTS',
  FETCH_POSTS_SUCCESS: 'posts/FETCH_POSTS_SUCCESS',
  FETCH_POSTS_FAILURE: 'posts/FETCH_POSTS_FAILURE',
  FETCH_POST: 'posts/FETCH_POST',
  FETCH_POST_SUCCESS: 'posts/FETCH_POST_SUCCESS',
  FETCH_POST_FAILURE: 'posts/FETCH_POST_FAILURE',
}
